### ISSUE TITLE
Documentation is mentioning --deps although --dep must be used

### ISSUE THREAD

**Issue by apupier** [jbangdev/jbang#1335] opened 2022-04-15 13:13 UTC
**Describe the bug**
```
> Executing task: jbang -Dcamel.jbang.version=3.16.0 camel@apache/camel run .vscode/launch.json --max-messages=10 --logging-level=info --reload --deps=org.apache.camel:camel-debug <

Unknown option: '--deps=org.apache.camel:camel-debug'
Possible solutions: --dep, --dependency
```

https://www.jbang.dev/documentation/guide/latest/cli/jbang-run.html#_options
```
--deps=<dependencies>

    Add additional dependencies (Use commas to separate them).
```

**To Reproduce**

**Expected behavior**

documentation shoudl be in sync. i do not know what is the best to change to have it working --deps or to modify the documentation. Deps is what is used inside the file so make sense to be in sync. On the other hand, it is introducing a breaking change (unless we support both for a time?)

**JBang version**
Paste output of `jbang version --verbose`

```
[jbang] jbang version 0.92.2
Cache: /home/apupier/.jbang/cache
Config: /home/apupier/.jbang
Repository:/home/apupier/.m2/repository
0.92.2
```

**Additional context**

**Comment by maxandersen** [comment] 2022-04-16 07:56
The flag name is "--deps" and it is to be *before* the script reference as anything coming after it is an argument to the script:

Your paste has the following parts:

command: `jbang` 
flags for jbang: `-Dcamel.jbang.version=3.16.0` 
script reference: `camel@apache/camel` 
arguments to your script: `run .vscode/launch.json --max-messages=10 --logging-level=info --reload --deps=org.apache.camel:camel-debug`

And when running `jbang camel@apache/camel run --help` we can see:
`      --dep, --dependency   Additional dependencies to add to the classpath`

Thus this is a camel issue not jbang.

I do suggest you allow `--deps` too assuming you actually support adding multiple dependencies as jbang cli does; if not the help should say "Additional dependency to add to the classpath"

**Comment by maxandersen** [comment] 2022-04-16 07:56
closing as not a bug in jbang afaics.

**Closed by maxandersen** 2022-04-16 07:56 UTC
Labels: bug

**Comment by apupier** [comment] 2022-04-19 07:32
Thanks for the explanation.

for information, I reported https://issues.apache.org/jira/browse/CAMEL-17981
