### ISSUE TITLE
Failed to copy SpringBoot's application.properties with Alias Catalogs

### ISSUE THREAD

**Issue by linux-china** [jbangdev/jbang#534] opened 2020-11-22 05:06 UTC
The code is here https://github.com/linux-china/jbang-catalog/

it works well to execute script with normal command style.

```
$ jbang src/jbang/springBoot/demo1/SpringBootApp.java
```

Add alias in jbang-catalog.json file as following:  

```
{
  "aliases": {
    "SpringBootApp": {
      "script-ref": "src/jbang/springBoot/demo1/SpringBootApp.java"
    }
  }
}
```

then execute with alias: 

```
$ jbang cache clear --all
$ jbang SpringBootApp
```

and I get the following exception: 

```
[jbang] Resolving dependencies...
[jbang]     Resolving org.springframework.boot:spring-boot-starter:2.4.0...Done
[jbang] Dependencies resolved
[jbang] [ERROR] Could not copy application.properties to /Users/xxx/.jbang/cache/jars/SpringBootApp.java.af1e76d599ee123f47fd478ca1c305952f9aab34423eadb6137541c7bd39fc60/application.properties
[jbang] Run with --verbose for more details
```

**Comment by quintesse** [comment] 2020-11-22 12:03
Hi @linux-china , could you perhaps rerun with `--verbose` and post that output as well? Thanks!

**Comment by linux-china** [comment] 2020-11-22 19:32
stack trace with verbose

```
❯ jbang --verbose SpringBootApp
[jbang] Reading aliases from /Users/linux_china/.jbang/jbang-catalog.json
[jbang] Reading aliases from /Users/linux_china/github/linux_china/jbang-catalog/jbang-catalog.json
[jbang] System Java version detected as 8
[jbang] System Java version matches requested version 8
[jbang] Copying application.properties to /Users/linux_china/.jbang/cache/jars/SpringBootApp.java.af1e76d599ee123f47fd478ca1c305952f9aab34423eadb6137541c7bd39fc60/application.properties
[jbang] Deleting /Users/linux_china/.jbang/cache/jars/SpringBootApp.java.af1e76d599ee123f47fd478ca1c305952f9aab34423eadb6137541c7bd39fc60
[jbang] [ERROR] Could not copy application.properties to /Users/linux_china/.jbang/cache/jars/SpringBootApp.java.af1e76d599ee123f47fd478ca1c305952f9aab34423eadb6137541c7bd39fc60/application.properties
dev.jbang.ExitException: Could not copy application.properties to /Users/linux_china/.jbang/cache/jars/SpringBootApp.java.af1e76d599ee123f47fd478ca1c305952f9aab34423eadb6137541c7bd39fc60/application.properties
	at dev.jbang.FileRef.copy(FileRef.java:68)
	at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:172)
	at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:129)
	at dev.jbang.cli.Run.prepareArtifacts(Run.java:70)
	at dev.jbang.cli.Run.doCall(Run.java:59)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:80)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at dev.jbang.Main.main(Main.java:14)
Caused by: java.nio.file.NoSuchFileException: application.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at dev.jbang.FileRef.copy(FileRef.java:66)
	... 14 more
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues
```

**Comment by maxandersen** [comment] 2020-11-22 22:52
i can reproduce but I could have sworn we had a test for this. checking.

**Comment by maxandersen** [comment] 2020-11-22 22:54
ok so `jbang https://github.com/linux-china/jbang-catalog/blob/master/src/jbang/springBoot/demo1/SpringBootApp.java` works or rather it runs but fail due to other issues I guess:

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.0)

2020-11-22 23:52:59.417  INFO 95146 --- [           main] demo1.SpringBootApp                      : Starting SpringBootApp using Java 11.0.8 on darkbeard.home with PID 95146 (/Users/max/.jbang/cache/jars/SpringBootApp.java.af1e76d599ee123f47fd478ca1c305952f9aab34423eadb6137541c7bd39fc60.jar started by max in /Users/max/code/personal/jbang)
2020-11-22 23:52:59.419  INFO 95146 --- [           main] demo1.SpringBootApp                      : No active profile set, falling back to default profiles: default
2020-11-22 23:52:59.729  WARN 95146 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBootApp': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'nick' in value "${nick}"
2020-11-22 23:52:59.735  INFO 95146 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-11-22 23:52:59.753 ERROR 95146 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBootApp': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'nick' in value "${nick}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1415) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:608) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925) ~[spring-context-5.3.1.jar:5.3.1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.1.jar:5.3.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.0.jar:2.4.0]
	at demo1.SpringBootApp.main(SpringBootApp.java:17) ~[SpringBootApp.java.af1e76d599ee123f47fd478ca1c305952f9aab34423eadb6137541c7bd39fc60.jar:na]
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'nick' in value "${nick}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:178) ~[spring-core-5.3.1.jar:5.3.1]
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124) ~[spring-core-5.3.1.jar:5.3.1]
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239) ~[spring-core-5.3.1.jar:5.3.1]
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210) ~[spring-core-5.3.1.jar:5.3.1]
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175) ~[spring-context-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:931) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1308) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.1.jar:5.3.1]
	... 17 common frames omitted
```


so I think that the resolving in the case of alias are resolving relative to the alias rather than the main file.....thats my hunch atm.

**Comment by maxandersen** [comment] 2020-11-24 07:16
fixed in master! will do a bug fix release now .

**Closed by maxandersen** 2020-11-24 07:16 UTC
