### ISSUE TITLE
Unable to generate java file when using chat-gpt

### ISSUE THREAD

**Issue by sshaaf** [jbangdev/jbang#1612] opened 2023-04-14 16:51 UTC
**Describe the bug**
Unable to generate java file when using chat-gpt with --preview

**To Reproduce**
1. set OPENAI_API_KEY
2. run the following command
3. ` jbang --preview --verbose init jokes.java "print a random chuck norris joke fetched from the api service providing free jokes API" `

**Expected behavior**
should create jokes.java

**JBang version**
Paste output of 
`
[jbang] [0:377] jbang version 0.106.1
[jbang] [0:391] Reading catalog from /home/sysh/.jbang/implicit-catalog.json
[jbang] [0:442] Reading catalog from classpath:/jbang-catalog.json
[jbang] [0:445] JBangGPT Preview activated
[jbang] [0:445] [WARN] The result can vary greatly. Sometimes it works - other times it is just for inspiration or a good laugh.
[jbang] [0:513] Requesting HTTP GET https://www.jbang.dev/releases/latest/download/version.txt
[jbang] [0:513] Headers {User-Agent=[JBang/0.106.1 (Linux/6.2.9-200.fc37.x86_64/amd64) Java/20/Oracle Corporation]}
[jbang] [0:706] ChatGPT prompt {temperature=0.8, messages=[{role=system, content=You are to generate a response that only contain code that is written in a file ending in java in the style of jbang. The main class must be named jokes . Add no additional text.You can put comments in the code.}, {role=user, content=print a random chuck norris joke fetched from the api service providing free jokes api}], model=gpt-3.5-turbo}
[jbang] [0:730] Redirected to: https://github.com/jbangdev/jbang/releases/latest/download/version.txt
[jbang] [0:855] Redirected to: https://github.com/jbangdev/jbang/releases/download/v0.106.1/version.txt
[jbang] [0:913] [ERROR] Cannot invoke "java.util.List.stream()" because "result.choices" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "result.choices" is null
	at dev.jbang.cli.Init.fetchGptResponse(Init.java:221)
	at dev.jbang.cli.Init.doCall(Init.java:92)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:147)
	at dev.jbang.cli.JBang$3.handle(JBang.java:142)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] [0:914] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues

`

**Additional context**
Using Linux, fish, 
openjdk version "20" 2023-03-21
OpenJDK Runtime Environment (build 20+36-2344)
OpenJDK 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)

**Comment by maxandersen** [comment] 2023-04-16 17:33
duplicate of #1610

**Closed by maxandersen** 2023-04-16 17:33 UTC
Labels: bug
