### ISSUE TITLE
ConcurrentModificationException when declaring the same repo twice

### ISSUE THREAD

**Issue by jmini** [jbangdev/jbang#1293] opened 2022-03-11 10:43 UTC
**Describe the bug**
This is probably a corner case, but I got an error when declaring the same repository twice.

**To Reproduce**
In my case it was once in the source file:
```
//REPOS acme=https://maven.acme.local/maven
```

And once on the command line:
`--repos acme=https://maven.acme.local/maven`

But you can also reproduce it with 2 lines in the source script:
```
//REPOS acme=https://maven.acme.local/maven
//REPOS acme=https://maven.acme.local/maven
```

**Expected behavior**
Maybe a clear error message?
Or if the value is the same, ignore the second declaration?

**JBang version**
0.91.0

**Additional context**
Stacktrace:
```
[jbang] [ERROR] public class java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.addRemoteRepo(MavenWorkingSessionImpl.java:315)
	at org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenResolverSystemImpl.withRemoteRepo(ConfigurableMavenResolverSystemImpl.java:59)
	at org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenResolverSystemImpl.withRemoteRepo(ConfigurableMavenResolverSystemImpl.java:36)
	at dev.jbang.dependencies.MavenRepo.apply(MavenRepo.java:32)
	at dev.jbang.dependencies.DependencyUtil.lambda$resolveDependenciesViaAether$1(DependencyUtil.java:152)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at dev.jbang.dependencies.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:152)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:122)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:71)
	at dev.jbang.dependencies.DependencyResolver.resolve(DependencyResolver.java:67)
	at dev.jbang.source.SourceSet.getClassPath(SourceSet.java:260)
	at dev.jbang.source.builders.BaseBuilder.compile(BaseBuilder.java:135)
	at dev.jbang.source.builders.BaseBuilder.build(BaseBuilder.java:108)
	at dev.jbang.cli.BaseBuildCommand.buildIfNeeded(BaseBuildCommand.java:49)
	at dev.jbang.cli.Run.prepareArtifacts(Run.java:122)
	at dev.jbang.cli.Run.doCall(Run.java:94)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:93)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:15)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.JBang$3.handle(JBang.java:145)
	at dev.jbang.cli.JBang$3.handle(JBang.java:140)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
```

**Comment by quintesse** [comment] 2022-03-11 11:42
Good catch @jmini , thanks. Fixed it. Should be available in next update.

**Comment by grumpyf0x48** [comment] 2022-03-26 15:48
Cannot reproduce with JBang 0.92.2

**Comment by maxandersen** [comment] 2022-04-07 08:31
marking as fixed

**Closed by maxandersen** 2022-04-07 08:31 UTC
Labels: bug
