### ISSUE TITLE
on second run flags like //JAVA 14 are ignored

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#727] opened 2021-02-15 11:06 UTC
Example: https://github.com/galderz/qollider/blob/master/examples/jdk.java

when no jar built then it works. 

after that jbang jdk.java nor jbang --fresh jdk.java works and jbang keeps running using java 11.

﻿

**Comment by quintesse** [comment] 2021-02-15 11:28
@maxandersen are you sure this description is correct? I can't reproduce it in the way you describe. For me it works when a) no jar currently exists or b) when specifying `--fresh`. It only fails when executing the script a second, third, etc time (without `--fresh`). Can you confirm?

**Comment by quintesse** [comment] 2021-02-15 11:33
Btw, I'm testing with `jbang records@jbangdev/jbang-examples` myself because the script from the description is a bit "heavy" for testing purposes.

Can you @galderz and @maxandersen confirm that this script shows the same problem?

**Comment by quintesse** [comment] 2021-02-15 11:35
Using `jbang info tools records@jbangdev/jbang-examples` at least shows the correct information, which is that the JAR was compiled with version 14 (which is therefore the minimum required version). Which suggests the problem is when that information is ignored somehow in follow-up executions.

**Comment by galderz** [comment] 2021-02-17 10:50
> Can you @galderz and @maxandersen confirm that this script shows the same problem?

Yes it does:

```
❯ jbanging
0.66.0.2

❯ jbang records@jbangdev/jbang-examples
[jbang] Building jar...
Note: /home/g/.jbang/cache/urls/840f198a717c4083720e24008f34eb51252c58e5bb387da0508851af553f2415/records.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
[jbang] There is a new version of jbang available!
[jbang] You have version 0.66.0.2 and 0.66.1 is the latest.
[jbang] Use your package manager to update jbang to the latest version,
[jbang] or visit https://jbang.dev to download and install it yourself.
Point[x=2, y=4]

❯ jbang records@jbangdev/jbang-examples
Error: LinkageError occurred while loading main class records
	java.lang.UnsupportedClassVersionError: records (class file version 58.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 55.65535
```

**Comment by galderz** [comment] 2021-02-17 10:51
It seems like it's fixed in master now:

```
❯ jbanging
0.66.1.1

❯ jbang records@jbangdev/jbang-examples
[jbang] Building jar...
Note: /home/g/.jbang/cache/urls/840f198a717c4083720e24008f34eb51252c58e5bb387da0508851af553f2415/records.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
Point[x=2, y=4]

❯ jbang records@jbangdev/jbang-examples
Point[x=2, y=4]
```

**Comment by maxandersen** [comment] 2021-02-17 11:43
Whoops forgot to close. This is fixed in latest jbang. Please update @galderz :)

**Closed** 2021-02-18 23:16 UTC
