### ISSUE TITLE
DependencyResolutionException: Could not find artifact org.codehaus.groovy:groovy-all:jar:3.0.9 in mavencentral 

### ISSUE THREAD

**Issue by linux-china** [jbangdev/jbang#1137] opened 2021-12-19 18:25 UTC
Hello.java with following code:

```
//DEPS com.puravida-software.groogle:groogle-gmail:3.0.0

public class Hello {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
```

Then run `jbang --verbose Hello.java`, and stacktrace as following:  

```
[jbang] jbang version 0.84.2
[jbang] System Java version detected as 8
[jbang] System Java version matches requested version 8
[jbang] Resolving dependencies...
[jbang]     Resolving com.puravida-software.groogle:groogle-gmail:jar:3.0.0...[jbang] Deleting folder /Users/xxx/.jbang/cache/jars/Hello.java.1b8891a13188b9d858e3604abebb6c32a5efe899139223057e5ded5b2d4b0a4a.jar.tmp
[jbang] [ERROR] Could not resolve dependency
dev.jbang.cli.ExitException: Could not resolve dependency
	at dev.jbang.dependencies.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:202)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:113)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:62)
	at dev.jbang.dependencies.DependencyResolver.resolve(DependencyResolver.java:67)
	at dev.jbang.source.RunContext.resolveClassPath(RunContext.java:305)
	at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:152)
	at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:127)
	at dev.jbang.cli.BaseBuildCommand.buildIfNeeded(BaseBuildCommand.java:91)
	at dev.jbang.cli.Run.prepareArtifacts(Run.java:100)
	at dev.jbang.cli.Run.doCall(Run.java:76)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.JBang$3.handle(JBang.java:135)
	at dev.jbang.cli.JBang$3.handle(JBang.java:130)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: org.jboss.shrinkwrap.resolver.api.NoResolvedResultException: Unable to collect/resolve dependency tree for a resolution due to: Could not find artifact org.codehaus.groovy:groovy-all:jar:3.0.9 in mavencentral (https://repo1.maven.org/maven2/), caused by: Could not find artifact org.codehaus.groovy:groovy-all:jar:3.0.9 in mavencentral (https://repo1.maven.org/maven2/)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.wrapException(MavenWorkingSessionImpl.java:503)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:242)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.using(MavenStrategyStageBaseImpl.java:70)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:52)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:39)
	at dev.jbang.dependencies.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:192)
	... 20 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.codehaus.groovy:groovy-all:jar:3.0.9 in mavencentral (https://repo1.maven.org/maven2/)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:357)
	at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.resolveDependencies(MavenRepositorySystem.java:121)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:239)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.codehaus.groovy:groovy-all:jar:3.0.9 in mavencentral (https://repo1.maven.org/maven2/)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:340)
	... 26 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.codehaus.groovy:groovy-all:jar:3.0.9 in mavencentral (https://repo1.maven.org/maven2/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:644)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:499)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401)
	... 28 more
[jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

Yes,  `com.puravida-software.groogle:groogle-gmail:3.0.0`  contains `org.codehaus.groovy:groovy-all:3.0.9` dependency. 

 https://repo1.maven.org/maven2/com/puravida-software/groogle/groogle-gmail/3.0.0/groogle-gmail-3.0.0.pom

Is it caused by packaging pom?  

```
<groupId>org.apache.groovy</groupId>
<artifactId>groovy-all</artifactId>
<version>4.0.0-rc-1</version>
<packaging>pom</packaging>
```

**Comment by maxandersen** [comment] 2021-12-19 22:26
This would break in maven too. 

I wonder what groovy grape does differently here ?

**Comment by maxandersen** [comment] 2021-12-20 08:49
okey so this fails in maven too.

```
[ERROR] Failed to execute goal on project my-app: Could not resolve dependencies for project corp.acme.app:my-app:jar:1.0-SNAPSHOT: Could not find artifact org.codehaus.groovy:groovy-all:jar:3.0.9 in jboss-enterprise-maven-repository (https://maven.repository.redhat.com/ga/) -> [Help 1]
```

The metadata is borked for com.puravida-software.groogle:groogle-gmail:



```
mvn -f ~/.m2/repository/com/puravida-software/groogle/groogle-gmail/3.0.0/groogle-gmail-3.0.0.pom dependency:tree --debug
...
[DEBUG] com.puravida-software.groogle:groogle-gmail:jar:3.0.0
[DEBUG]    com.puravida-software.groogle:groogle-core:jar:3.0.0:compile
[DEBUG]    org.codehaus.groovy:groovy-all:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-ant:jar:3.0.9:compile
[DEBUG]          org.apache.ant:ant:jar:1.10.11:compile
[DEBUG]          org.apache.ant:ant-junit:jar:1.10.11:runtime
[DEBUG]          org.apache.ant:ant-launcher:jar:1.10.11:runtime
[DEBUG]          org.apache.ant:ant-antlr:jar:1.10.11:runtime
[DEBUG]       org.codehaus.groovy:groovy-astbuilder:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-cli-picocli:jar:3.0.9:compile
[DEBUG]          info.picocli:picocli:jar:4.6.1:runtime
[DEBUG]       org.codehaus.groovy:groovy-console:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-datetime:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-docgenerator:jar:3.0.9:compile
[DEBUG]          com.thoughtworks.qdox:qdox:jar:1.12.1:runtime
[DEBUG]       org.codehaus.groovy:groovy-groovydoc:jar:3.0.9:compile
[DEBUG]          com.github.javaparser:javaparser-core:jar:3.23.0:compile
[DEBUG]       org.codehaus.groovy:groovy-groovysh:jar:3.0.9:compile
[DEBUG]          jline:jline:jar:2.14.6:runtime
[DEBUG]       org.codehaus.groovy:groovy-jmx:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-json:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-jsr223:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-macro:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-nio:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-servlet:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-sql:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-swing:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-templates:jar:3.0.9:compile
[DEBUG]       org.codehaus.groovy:groovy-test:jar:3.0.9:compile
[DEBUG]          junit:junit:jar:4.13.2:compile
[DEBUG]             org.hamcrest:hamcrest-core:jar:1.3:compile
[DEBUG]       org.codehaus.groovy:groovy-test-junit5:jar:3.0.9:compile
[DEBUG]          org.junit.jupiter:junit-jupiter-api:jar:5.7.2:compile
[DEBUG]             org.opentest4j:opentest4j:jar:1.2.0:compile
[DEBUG]          org.junit.platform:junit-platform-launcher:jar:1.7.2:runtime
[DEBUG]             org.junit.platform:junit-platform-engine:jar:1.7.2:runtime
[DEBUG]                org.junit.platform:junit-platform-commons:jar:1.7.2:runtime
[DEBUG]          org.junit.jupiter:junit-jupiter-engine:jar:5.7.2:runtime
[DEBUG]       org.codehaus.groovy:groovy-testng:jar:3.0.9:compile
[DEBUG]          org.testng:testng:jar:7.4.0:runtime
[DEBUG]             com.beust:jcommander:jar:1.78:runtime
[DEBUG]             org.webjars:jquery:jar:3.5.1:runtime
[DEBUG]       org.codehaus.groovy:groovy-xml:jar:3.0.9:compile
[DEBUG]    com.google.api-client:google-api-client:jar:1.32.1:compile
[DEBUG]       com.google.oauth-client:google-oauth-client:jar:1.31.5:compile
[DEBUG]       com.google.http-client:google-http-client-gson:jar:1.39.2:compile
[DEBUG]          com.google.code.gson:gson:jar:2.8.6:compile
[DEBUG]       com.google.guava:guava:jar:30.1.1-android:compile
[DEBUG]          com.google.guava:failureaccess:jar:1.0.1:compile
[DEBUG]          com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[DEBUG]          com.google.code.findbugs:jsr305:jar:3.0.2:compile
[DEBUG]          org.checkerframework:checker-compat-qual:jar:2.5.5:compile
[DEBUG]          com.google.errorprone:error_prone_annotations:jar:2.5.1:compile
[DEBUG]          com.google.j2objc:j2objc-annotations:jar:1.3:compile
[DEBUG]       com.google.http-client:google-http-client-apache-v2:jar:1.39.2:compile
[DEBUG]       org.apache.httpcomponents:httpcore:jar:4.4.14:compile
[DEBUG]       org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[DEBUG]          commons-logging:commons-logging:jar:1.2:compile
[DEBUG]          commons-codec:commons-codec:jar:1.11:compile
[DEBUG]       com.google.http-client:google-http-client:jar:1.39.2:compile
[DEBUG]          io.opencensus:opencensus-api:jar:0.28.0:compile
[DEBUG]             io.grpc:grpc-context:jar:1.27.2:compile
[DEBUG]          io.opencensus:opencensus-contrib-http-util:jar:0.28.0:compile
[DEBUG]    com.google.oauth-client:google-oauth-client-jetty:jar:1.32.1:compile
[DEBUG]       com.google.oauth-client:google-oauth-client-java6:jar:1.32.1:compile
[DEBUG]    com.google.apis:google-api-services-gmail:jar:v1-rev98-1.25.0:compile
[DEBUG]    javax.mail:mail:jar:1.4:compile
[DEBUG]       javax.activation:activation:jar:1.1:compile
...
```

Cause is this line: https://gitlab.com/puravida-software/groogle/-/blob/master/groogle-core/build.gradle#L7
 
`compile 'org.codehaus.groovy:groovy-all:2.4.12'`

They use a pom file as a compile dependency which when translated into a pom.xml is done wrong. 

The issue is same/similar as #1065

I'm going to close this as a duplicate of the same problem.

**Closed by maxandersen** 2021-12-20 08:49 UTC
Labels: bug
