### ISSUE TITLE
documentation: Markdown example is actually Kotlin

### ISSUE THREAD

**Issue by jesuino** [jbangdev/jbang#1321] opened 2022-03-23 15:31 UTC
The documentation shows a Kotlin example when it should actually be a MD example:

![image](https://user-images.githubusercontent.com/359820/159736173-0521600c-12e9-4f90-bea1-42254b52bd65.png)

Link: 
https://www.jbang.dev/documentation/guide/latest/usage.html

**Comment by maxandersen** [comment] 2022-03-23 16:02
duplicate of #1239

**Closed by maxandersen** 2022-03-23 16:02 UTC
Labels: bug
