### ISSUE TITLE
jbang not on $PATH after sdkman install

### ISSUE THREAD

**Issue by ALRubinger** [jbangdev/jbang#442] opened 2020-10-14 11:27 UTC
```
alr@alr-tubescreamer ~ % sdk list jbang
================================================================================
Available Jbang Versions
================================================================================
   * 0.51.1              0.39.0              0.23.0              0.11.0
     0.51.0              0.38.0              0.22.0.2            0.10.0
     0.50.1              0.37.0              0.21.0              0.9.4
     0.50.0              0.36.1              0.20.0              0.9.3
     0.49.0              0.36.0              0.19.0              0.8.1
     0.48.0              0.35.1              0.18.0              0.7.5
     0.47.1              0.35.0              0.17.0              0.7.1
     0.47.0              0.34.1              0.16.2              0.7.0
     0.46.1              0.34.0              0.16.1              0.6.4.3
     0.46.0              0.33.0              0.16.0              0.6.1
     0.45.0              0.32.0              0.15.1              0.6.0.5
     0.44.2              0.31.0              0.15.0              0.5.0
     0.44.0              0.30.0              0.14.2              0.4.0.1
     0.43.0              0.29.1              0.14.0              0.3.2
     0.42.1              0.29.0              0.13.2              0.3.1
     0.42.0              0.28.0              0.13.1              0.2.1
     0.41.0              0.27.0              0.13.0              0.2.0.4
     0.40.2              0.26.0              0.12.2
     0.40.1              0.25.0              0.12.1
     0.40.0              0.24.0              0.11.1

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================

alr@alr-tubescreamer ~ % jbang
zsh: command not found: jbang

alr@alr-tubescreamer ~ % ls -l ~/.sdkman/candidates/jbang/0.51.1/bin
total 11664
-rwxr-xr-x  1 alr  staff     5399 Feb  1  1980 jbang
-rw-r--r--  1 alr  staff     5007 Feb  1  1980 jbang.cmd
-rw-r--r--  1 alr  staff  5946963 Feb  1  1980 jbang.jar
-rw-r--r--  1 alr  staff     6639 Feb  1  1980 jbang.ps1

alr@alr-tubescreamer ~ % echo $PATH
/Users/alr/.sdkman/candidates/maven/current/bin:/Users/alr/.sdkman/candidates/java/current/bin:/Users/alr/.nvm/versions/node/v14.5.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Installed, binary exists, but is not on the PATH like `mvn` and `java` are.

**Comment by quintesse** [comment] 2020-10-14 14:44
Could you try opening a new shell @ALRubinger ? I've noticed sometimes that SDKMAN doesn't properly update until a new shell is used.

**Comment by maxandersen** [comment] 2020-10-14 21:40
back at computer so I can show how it is supposed to look when setup:

```
❯ sdk list jbang
==== BROADCAST =================================================================
* 2020-10-14: gradle 6.7 available on SDKMAN!
* 2020-10-14: mulefd 0.7.4 available on SDKMAN! https://git.io/JTmGy
* 2020-10-14: mulefd 0.7.4 available on SDKMAN! https://git.io/JTmGy
================================================================================
================================================================================
Available Jbang Versions
================================================================================
     0.51.1              0.39.0              0.23.0              0.11.0         
     0.51.0            * 0.38.0              0.22.0.2            0.10.0         
 > * 0.50.1              0.37.0              0.21.0              0.9.4          
   * 0.50.0            * 0.36.1              0.20.0              0.9.3          
     0.49.0              0.36.0              0.19.0              0.8.1          
   * 0.48.0              0.35.1              0.18.0              0.7.5          
   * 0.47.1              0.35.0              0.17.0              0.7.1          
     0.47.0              0.34.1              0.16.2              0.7.0          
     0.46.1            * 0.34.0              0.16.1              0.6.4.3        
     0.46.0              0.33.0              0.16.0              0.6.1          
     0.45.0              0.32.0              0.15.1              0.6.0.5        
     0.44.2              0.31.0              0.15.0              0.5.0          
     0.44.0              0.30.0              0.14.2              0.4.0.1        
     0.43.0              0.29.1              0.14.0              0.3.2          
   * 0.42.1              0.29.0              0.13.2              0.3.1          
   * 0.42.0              0.28.0              0.13.1              0.2.1          
     0.41.0              0.27.0              0.13.0              0.2.0.4        
   * 0.40.2              0.26.0              0.12.2                             
     0.40.1              0.25.0              0.12.1                             
   * 0.40.0              0.24.0              0.11.1                             

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
```

notice how I have `>` and you don't.

That indicates you haven't said yes to use jbang OR you haven't source'd/restarted your shell to have it pick up the setup where sdk have added `jbang` to a path.

If I do `sdk install jbang` I get this:

```
❯ sdk install jbang

Downloading: jbang 0.51.1

In progress...

###################################################################################################################################################################################################################################### 100.0%###################################################################################################################################################################################################################################### 100.0%

Installing: jbang 0.51.1
Done installing!

Do you want jbang 0.51.1 to be set as default? (Y/n): y
Setting jbang 0.51.1 as default.
```

if I don't answer Y then nothing is changed/set on my path.

**Comment by maxandersen** [comment] 2020-10-14 21:51
I just tried removing and reinstalling sdkman I just can't reproduce it if I follow the steps outlined on https://sdkman.io/install and https://www.jbang.dev/download ... if you could figure out what steps you did to end up without sdkman having a jbang marked as used would be great.

**Comment by ALRubinger** [comment] 2020-10-20 02:48
@quintesse; Used a new shell; it wouldn't fix. Odd.

Took @maxandersen's advice to uninstall, reinstall - everything works like a charm.

Cannot reproduce myself now, either. Done several uninstall/reinstall loops to try to replicate.

Weird. I guess close until we see it again?

**Comment by maxandersen** [comment] 2020-10-25 08:42
closing until we meet again!

**Closed by maxandersen** 2020-10-25 08:42 UTC
