### ISSUE TITLE
Reusing code from multiple scripts

### ISSUE THREAD

**Issue by OLibutzki** [jbangdev/jbang#276] opened 2020-09-02 05:06 UTC
Hi, 

I have two jbang scripts which share a couple of methods. AFAIK I know I have these options to solve this:
- Merging both scripts into one script (I prefer to have two scripts)
- Duplicating the shared code in both scripts (not a good idea)
- Externalizing the shared code, buildung a jar and using that jar as a dependency (doing this I would lose nearly all the benefits of jbang)

As you can see all alternatives are not perfect. It would be great if jbang could provide a convenient solution for this problem.

Thanks.

Kind regards
Oliver

**Comment by abelsromero** [comment] 2020-09-02 06:40
I think you may be interested in this one: https://github.com/jbangdev/jbang/issues/39

**Comment by maxandersen** [comment] 2020-09-02 07:07
100% agree :) duplicate of #39

**Comment by maxandersen** [comment] 2020-09-02 07:08
Note, we might be able to do //DEPS xyz.java sooner than multiple source.

**Closed** 2020-09-02 07:07 UTC

**Comment by OLibutzki** [comment] 2020-09-02 07:23
I agree, that's a duplicate. #39 covers my needs perfectly.
